#!/bin/bash
set -e

VARS_FILE=".gh_vars"
TFVARS_FILE="terraform/terraform.tfvars"

echo "Downloading variables from GitHub..."
gh variable list --json name,value | jq -r '.[] | "\(.name)=\(.value)"' > "$VARS_FILE"

echo "Creating $TFVARS_FILE..."
{
    echo "# Generated by manage_variables.sh - DO NOT COMMIT"
    echo "cloudflare_account_id = \"$(grep CLOUDFLARE_ACCOUNT_ID= "$VARS_FILE" | cut -d= -f2- | sed 's/^= *//')\""
    echo "cloudflare_api_token = \"$(grep CLOUDFLARE_API_TOKEN= "$VARS_FILE" | cut -d= -f2- | sed 's/^= *//')\""
    echo "cloudflare_zone_id = \"$(grep CLOUDFLARE_ZONE_ID= "$VARS_FILE" | cut -d= -f2- | sed 's/^= *//')\""
    echo "project_name = \"$(grep PROJECT_NAME= "$VARS_FILE" | cut -d= -f2- | sed 's/^= *//')\""
} > "$TFVARS_FILE"

echo "Done!"
rm -f "$VARS_FILE"
